# Generated by Django 2.2 on 2019-10-29 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_auto_20191029_2327'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
