# Generated by Django 2.2 on 2019-10-30 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0013_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='phonenumber',
            new_name='quantity',
        ),
    ]
